/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SmPr4ESRj1f
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function CC() {
  return (
    (<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Credit Calculator</CardTitle>
          <CardDescription>Add courses and see the total required and elected credits.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="grid grid-cols-[1fr_auto] items-center gap-2">
              <Input name="name" placeholder="Course Name" />
              <Button>Add</Button>
            </div>
            <div className="grid grid-cols-[1fr_1fr] gap-2">
              <Select name="credits">
                <SelectTrigger>
                  <SelectValue placeholder="Credits" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">0</SelectItem>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                  <SelectItem value="6">6</SelectItem>
                </SelectContent>
              </Select>
              <Select name="type">
                <SelectTrigger>
                  <SelectValue placeholder="Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="required">Required</SelectItem>
                  <SelectItem value="elected">Elected</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <span>Required Credits:</span>
                <span />
              </div>
              <div className="flex items-center justify-between">
                <span>Elected Credits:</span>
                <span />
              </div>
            </div>
            <div className="grid gap-2" />
          </div>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Credit Calculator</CardTitle>
          <CardDescription>Add courses and see the total required and elected credits.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="grid grid-cols-[1fr_auto] items-center gap-2">
              <Input name="name" placeholder="Course Name" />
              <Button>Add</Button>
            </div>
            <div className="grid grid-cols-[1fr_1fr] gap-2">
              <Select name="credits">
                <SelectTrigger>
                  <SelectValue placeholder="Credits" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">0</SelectItem>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                  <SelectItem value="6">6</SelectItem>
                </SelectContent>
              </Select>
              <Select name="type">
                <SelectTrigger>
                  <SelectValue placeholder="Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="required">Required</SelectItem>
                  <SelectItem value="elected">Elected</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <span>Required Credits:</span>
                <span />
              </div>
              <div className="flex items-center justify-between">
                <span>Elected Credits:</span>
                <span />
              </div>
            </div>
            <div className="grid gap-2" />
          </div>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Credit Calculator</CardTitle>
          <CardDescription>Add courses and see the total required and elected credits.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="grid grid-cols-[1fr_auto] items-center gap-2">
              <Input name="name" placeholder="Course Name" />
              <Button>Add</Button>
            </div>
            <div className="grid grid-cols-[1fr_1fr] gap-2">
              <Select name="credits">
                <SelectTrigger>
                  <SelectValue placeholder="Credits" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">0</SelectItem>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                  <SelectItem value="6">6</SelectItem>
                </SelectContent>
              </Select>
              <Select name="type">
                <SelectTrigger>
                  <SelectValue placeholder="Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="required">Required</SelectItem>
                  <SelectItem value="elected">Elected</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <span>Required Credits:</span>
                <span />
              </div>
              <div className="flex items-center justify-between">
                <span>Elected Credits:</span>
                <span />
              </div>
            </div>
            <div className="grid gap-2" />
          </div>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Credit Calculator</CardTitle>
          <CardDescription>Add courses and see the total required and elected credits.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="grid grid-cols-[1fr_auto] items-center gap-2">
              <Input name="name" placeholder="Course Name" />
              <Button>Add</Button>
            </div>
            <div className="grid grid-cols-[1fr_1fr] gap-2">
              <Select name="credits">
                <SelectTrigger>
                  <SelectValue placeholder="Credits" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">0</SelectItem>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="4">4</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                  <SelectItem value="6">6</SelectItem>
                </SelectContent>
              </Select>
              <Select name="type">
                <SelectTrigger>
                  <SelectValue placeholder="Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="required">Required</SelectItem>
                  <SelectItem value="elected">Elected</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <span>Required Credits:</span>
                <span />
              </div>
              <div className="flex items-center justify-between">
                <span>Elected Credits:</span>
                <span />
              </div>
            </div>
            <div className="grid gap-2" />
          </div>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Credit Summary</CardTitle>
          <CardDescription>Total required and elected credits.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="flex items-center justify-between">
              <span>Required Credits:</span>
              <span />
            </div>
            <div className="flex items-center justify-between">
              <span>Elected Credits:</span>
              <span />
            </div>
            <div className="flex items-center justify-between">
              <span>Total Credits:</span>
              <span />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>)
  );
}
