/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pqF7LbpW1U0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import Link from "next/link";

export function Homepage({ onLearnMoreClick }) {
  return (
    <main className="flex flex-col gap-12 py-12 md:py-24 lg:py-32">
      <section className="container px-4 md:px-6">
        <div className="grid gap-6 md:grid-cols-2 md:gap-12">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              小工具網站
            </h2>
            <p className="text-gray-500 md:text-xl dark:text-gray-400">
              可以幫助你計算GPA和查看天氣
            </p>
          </div>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>開始使用</CardTitle>
              {/* <CardDescription>使用小工具來幫助您學習</CardDescription> */}
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="flex items-center gap-4">
                <ClipboardIcon className="w-8 h-8 text-gray-900 dark:text-gray-50" />
                <div>
                  {/* <h3 className="font-medium">GPA計算</h3> */}
                  <p className="text-gray-500 dark:text-gray-400">GPA計算機</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <CalendarIcon className="w-8 h-8 text-gray-900 dark:text-gray-50" />
                <div>
                  {/* <h3 className="font-medium">Calendar</h3> */}
                  <p className="text-gray-500 dark:text-gray-400">
                    查看天氣來安排你得行程
                  </p>
                </div>
              </div>
              {/* <div className="flex items-center gap-4">
                 <BarChartIcon className="w-8 h-8 text-gray-900 dark:text-gray-50" /> 
              </div> */}
            </CardContent>
            <CardFooter>
              <button className="inline-flex items-center gap-2 text-gray-900 hover:underline dark:text-gray-50">
                Learn More
              </button>
              <ArrowRightIcon className="w-4 h-4" />
            </CardFooter>
          </Card>
        </div>
      </section>
    </main>
  );
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  );
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}

function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  );
}
export default Homepage;
