/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pqF7LbpW1U0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import Link from "next/link";

export function Homepage({onButtonClick }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-powerblue-100 dark:bg-gray-900">
      <header className="w-full max-w-5xl px-4 py-8 mb-12">
        <h1 className="text-3xl font-bold text-center text-gray-900 dark:text-gray-100">
          Utility Hub
        </h1>
      </header>
      <div className="grid grid-cols-1 gap-8 sm:grid-cols-3 w-full max-w-5xl px-4">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 flex flex-col items-center justify-center">
          <CalculatorIcon className="w-12 h-12 text-gray-600 dark:text-gray-400 mb-4" />
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">
            GPA Calculator
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-400 mb-6">
            Easily calculate your grade point average.
          </p>
          <button className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" onClick={() => onButtonClick("GRADE")}>
            Calculator GPA
          </button>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 flex flex-col items-center justify-center">
          <CalculatorIcon className="w-12 h-12 text-gray-600 dark:text-gray-400 mb-4" />
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">
            Credit Calculator
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-400 mb-6">
            Determine your total earned credits.
          </p>
          <button className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" onClick={() => onButtonClick("CreditCalculator")}>
            Calculator Credits
          </button>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 flex flex-col items-center justify-center">
          <SunIcon className="w-12 h-12 text-gray-600 dark:text-gray-400 mb-4" />
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">
            Weather Lookup
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-400 mb-6">
            Check the current weather for any location.
          </p>
          <button className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" onClick={() => onButtonClick("SCW")}>
            Check Weather
          </button>
        </div>
      </div>
    </div>
  );
}

function CalculatorIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" />
      <line x1="8" x2="16" y1="6" y2="6" />
      <line x1="16" x2="16" y1="14" y2="18" />
      <path d="M16 10h.01" />
      <path d="M12 10h.01" />
      <path d="M8 10h.01" />
      <path d="M12 14h.01" />
      <path d="M8 14h.01" />
      <path d="M12 18h.01" />
      <path d="M8 18h.01" />
    </svg>
  );
}

function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  );
}
